python-to-control-OBS
UWARG/VideoSrcSimulator pull request #1
Opened 2021-08-18 13:18 UTC by mikashaw

Creates a scene, source, and records for 5 seconds.

2021-08-25 22:55 UTC, Shrinjay requested changes
Your code itself is fine, just needs to be productionized a bit, I've guided you on how to do this via comments but lmk if you have any questions, need clarification or explanation!

2021-08-25 22:55 UTC, Shrinjay commented on main.py
> +#!/usr/bin/env python
No real need to have these first two lines. It forces the interpreter to use python (rather than allowing the user to choose python or python3 or python2). We want the user to be able to choose.

2021-08-25 22:55 UTC, Shrinjay commented on main.py
> +print(sys.path.append('../'))
I don't think this line is necessary? Lmk if it breaks when you take it out, maybe it's looking at a different directory using this.

2021-08-25 22:55 UTC, Shrinjay commented on main.py
> +import logging
So all the imports should be in one place. What this means is that the logging config in the line below should be moved down below all the imports. The obswebsocket import on line 14 should be moved up to right below this import

2021-08-25 22:55 UTC, Shrinjay commented on main.py
> +from obswebsocket import obsws, requests  # noqa: E402
Move this up to be just below the other imports

2021-08-25 22:55 UTC, Shrinjay commented on main.py
> +ws.connect()
This is one of the things I meant when I said that this PR would be about "productionizing" this code, we need to isolate logic into functions. Since we need to maintain an instance of obsws, that makes up the application state that we need to maintain. When you need to maintain state, classes are your best friend. 

Therefore, let's restructure this. All the logic here is going to be part of a class called OBSConfig. Let's move the logic in lines 18-24 into the constructor for that class as such:
```
class OBSConfig:
  __init__(host, port, password):
     ws = obsws(host, port, password)
     ws.connect()
```

What this does is that it gives the user (whoever is writing the stream script) a websocket object all ready to go.

2021-08-25 22:55 UTC, Shrinjay commented on main.py
> +    ws.call(requests.CreateScene('test'))
Let's create a class method called setup_scene() that handles creating and setting the scene:
```
def setup_scene(self, scene_name):
   ... call to create scene and call to set current scene 
   as the scene you just created goes here...
```

2021-08-25 22:55 UTC, Shrinjay commented on main.py
> +    ws.call(requests.CreateSource('browser', 'browser_source', 'test', setVisible=True))
Let's move all the logic from lines 34-39 into a class method setup_file_source(scene, filepath).  It'll return the browser source properties. 

```
def setup_file_source(self, scene, source_name, filepath):
   self.ws.call(requests.CreateSource(source_name, 'browser_source', scene, setVisible=True))
   self.ws.call(requests.SetBrowserSourceProperties('browser', is_local_file=True, local_file=filepath))
   return self.ws.call(requests.getBrowserSourceProperties(source_name))
```

2021-08-25 22:55 UTC, Shrinjay commented on main.py
> +try:
Won't need this whole try/catch block in the class.

Btw, while this isn't relevent to this specific PR, a try/catch block isn't ideal for what you're trying to do here afaik. It's better to wait for keyboard input with input(...) or something similar rather than using a try catch block. try catch are for exceptions, so it's kind of anti-pattern to use them for something other than exceptions.

2021-08-25 22:55 UTC, Shrinjay commented on main.py
> +    #recording a 5-second snippet of the image
This can go into another class method called record(record_time)

```
def record(self, record_time):
   self.ws.call(requests.StartRecording())
   time.sleep(record_time)
   self.ws.call(requests.StopRecording())
```

Also, where does this record to? A directory we've already specified?

2021-08-25 22:55 UTC, Shrinjay commented on main.py
> +ws.disconnect()
Lastly, let's put the disconnect command in the class destructor

```
def __del__(self):
   self.ws.disconnect()
```
This will get called when the user deletes the object or closes the program.

2021-08-25 22:55 UTC, Shrinjay commented on main.py
> +#----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
So this code itself is solid, we just need to productionize it a bit. I want main.py to just contain  a class called OBSConfig. Then whoever uses this library can import it into their own file called script.py or whatever, and then use it. I'll go over how to do this in the other comments.

2021-08-27 23:26 UTC, mikashaw commented on main.py
> +#----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
ok perfect, yeah the code was a bit messy (I tried a lot of different things before getting it to work lol so there is just some leftover obsolete code) and sounds good, I'll get started right away!

2021-08-29 20:57 UTC, mikashaw commented on main.py
> +    #recording a 5-second snippet of the image
the location of recordings default to the OBS folder on your device, but it can be changed via output settings

2021-09-04 02:24 UTC, Shrinjay approved these changes

2021-09-04 02:24 UTC, merged